 # Create a Python virtual environment with the packages required 
 # conda env create -f environment.yml

name: kv2

dependencies:
  - python=3.6
  - numpy

  - pip:
    - opencv-python
    - pykinect2
    - open3d-python
